### ISSUE TITLE
Uncaught TypeError: Cannot read property 'plain' of undefined

### ISSUE THREAD

**Issue by SlimeQ** [noseglid/autocomplete-java-minus#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [autocomplete-java-minus](https://github.com/noseglid/autocomplete-java-minus) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property 'plain' of undefined

```
At /home/quincy/.atom/packages/autocomplete-java-minus/lib/provider.js:75

TypeError: Cannot read property 'plain' of undefined
    at Provider.getSuggestions (/home/quincy/.atom/packages/autocomplete-java-minus/lib/provider.js:75:29)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -5:18.7.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -5:17.5.0 core:save (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -5:10.4.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -5:09.2.0 core:save (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -5:06.3.0 git-plus:menu (atom-text-editor.editor.power-mode.is-focused)
  3x -5:05.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:04.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:00.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused.power-mode.autocomplete-active)
     -4:54.4.0 editor:newline (atom-text-editor.editor.is-focused.power-mode)
     -4:53.8.0 core:backspace (atom-text-editor.editor.is-focused.power-mode)
     -4:53.6.0 core:save (atom-text-editor.editor.is-focused.power-mode)
     -1:14.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.power-mode.is-focused)
     -1:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.power-mode.is-focused)
  2x -0:28.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:25.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.class"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
autocomplete-java-minus, v0.10.0
color-tabs, v0.1.8
git-plus, v5.15.0
java-importer, v1.4.1
language-gradle, v0.0.3
language-groovy, v0.6.0
linter, v1.11.11
linter-javac, v1.9.4
merge-conflicts, v1.4.4

# Dev
No dev packages
```

**Comment by noseglid** [comment]
You must install `java-classpath-registry`. I'm working on an umbrella project to get all the dependencies right.

Pro tip: also install `java-import-wiz` for auto-imports and organizing.
