### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ashkitten** [noseglid/autocomplete-java-minus#4]
[Enter steps to reproduce below:]
1. type @Override
2. begin typing whatever below that

**Atom Version**: 1.8.0
**System**: linux 4.6.2-1-ARCH
**Thrown From**: [autocomplete-java-minus](https://github.com/noseglid/autocomplete-java-minus) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/ash/.atom/packages/autocomplete-java-minus/lib/entryfinders/method-local-fields.js:27

TypeError: Cannot read property 'length' of undefined
    at PlainEntryFinder.getMethodLocalFields (/home/ash/.atom/packages/autocomplete-java-minus/lib/entryfinders/method-local-fields.js:27:36)
    at PlainEntryFinder.getLocalFieldSuggestions (/home/ash/.atom/packages/autocomplete-java-minus/lib/entryfinders/plain-entry-finder.js:15:14)
    at PlainEntryFinder.get (/home/ash/.atom/packages/autocomplete-java-minus/lib/entryfinders/plain-entry-finder.js:60:12)
    at Provider.getSuggestions (/home/ash/.atom/packages/autocomplete-java-minus/lib/provider.js:75:36)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -1:48.2.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:44.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.4.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:36.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:21.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:11.9.0 susave:save (atom-text-editor.editor.is-focused)
  3x -0:06.4.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "highlight-selected",
      "minimap-highlight-selected",
      "tab-preview",
      "activate-power-mode",
      "linter-luacheck"
    ],
    "themes": [
      "one-dark-ui",
      "purple-haze-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-cursor-indent, v0.1.1
atom-minify, v0.7.5
atom-notifier, v0.5.0
atom-yeoman, v0.3.15
atomic-chrome, v0.3.0
autocomplete-java-minus, v0.10.0
bottom-dock, v0.4.4
build, v0.64.0
build-gradle, v0.6.0
build-love, v0.1.0
busy, v0.5.0
file-icons, v1.7.15
fold-lines, v0.2.0
java-classpath-registry, v0.3.0
java-import-wiz, v0.5.0
java-plus, v0.1.0
json-schema, v0.1.15
language-gradle, v0.0.3
language-ini-desktop, v1.18.2
language-json-comments, v0.16.3
language-lua, v0.9.4
language-x86-64-assembly, v2.1.15
linter, v1.11.14
linter-lua, v1.0.2
linter-manager, v0.2.12
markdown-preview-plus, v2.4.0
minimap, v4.24.6
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
omnisharp-atom, v0.30.0
php-cs-fixer, v2.5.6
pigments, v0.29.2
purple-haze-syntax, v1.5.0
remember-folds, v0.1.0
susave, v0.4.0
svg-preview, v0.7.4

# Dev
No dev packages
```

**Comment by noseglid** [comment]
This is because the tokens in the editor is not updated until the file is saved (which may cause it to be out of line). It will be fixed in the next release where tokens will be updated after each change in a separate thread.
