### ISSUE TITLE
Cant install this plugin

### ISSUE THREAD

**Issue by ThePhilderbeast** [noseglid/autocomplete-java-minus#8]
Im trying to install this plugin however im getting the following error output when it trys to install

```
npm WARN engine sb-exec@2.0.5: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\phill\\AppData\\Local\\atom\\app-1.9.8\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\phill\\AppData\\Local\\atom\\app-1.9.8\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\phill\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\phill\\.atom\\.apmrc" "install" "C:\\Users\\phill\\AppData\\Local\\Temp\\d-116712-9940-ixqw4o\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
```

**Comment by noseglid** [comment]
Odd. It does require the nodejs source to build the oniguruma dependency, but that should be bundled in Atom. Have you had any issues installing other plugins?

Only thing I can think of is re-installing Atom. What platform are you running on? I haven't tested on Windows, so if that's your platform there may be another issue.

**Comment by ThePhilderbeast** [comment]
No i haven't had issues with any other plugins, including a number of yours. I'm trying to get is as part of your java Plus if that helps, and the other dependencies all work properly.

**Comment by ThePhilderbeast** [comment]
Still happening on a clean install of Atom, running Windows 10

**Comment by LordZane** [comment]
I have the same problem, is their a place I can put the nodejs source manually?

**Comment by noseglid** [comment]
I don't think, or at least I do not know.
It seems as Atom is "supposed" to figure it out by setting the correct headers to the node version which it's running. But there [seems to be some issues](https://discuss.atom.io/t/how-to-build-uses-a-native-node-package-with-an-atom-package/17437).

This seem to be isolated to the windows platform.

I've attempted to update the `first-mate` package (which is the one that depends on oniguruma). Can you test if this still is an issue with `v0.14.0` ?

**Comment by ThePhilderbeast** [comment]
still an issue,

luckily Atom try's to install this every time I open it so if something changes ill know straight away..........

**Comment by noseglid** [comment]
Is it the same error message?

**Comment by ThePhilderbeast** [comment]
only thing that has changed is the following line has had the --production switch adde

`"C:\\Users\\phill\\AppData\\Local\\Temp\\d-116724-13008-qaltdh\\package.tgz" "--target=0.37.8" "--arch=ia32" "--production"`

**Comment by noseglid** [comment]
Could you please post the full error output again?

**Comment by ThePhilderbeast** [comment]
```
C:\Users\phill\.atom\packages\build\node_modules\atom-package-deps\lib\view.js:65 [Package-Deps] Unable to install autocomplete-java-minus , Error: > oniguruma@6.1.0 install C:\Users\phill\AppData\Local\Temp\apm-install-dir-116724-7044-17na59k\node_modules\autocomplete-java-minus\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\phill\AppData\Local\Temp\apm-install-dir-116724-7044-17na59k\node_modules\autocomplete-java-minus\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\phill\AppData\Local\atom\app-1.9.9\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

npm WARN engine sb-exec@2.0.5: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\phill\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\phill\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\phill\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\phill\\.atom\\.apmrc" "install" "C:\\Users\\phill\\AppData\\Local\\Temp\\d-116724-7044-1qulsk4\\package.tgz" "--target=0.37.8" "--arch=ia32" "--production"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.complete @ C:\Users\phill\.atom\packages\build\node_modules\atom-package-deps\lib\view.js:65(anonymous function) @ C:\Users\phill\.atom\packages\build\node_modules\atom-package-deps\lib\index.js:18step @ C:\Users\phill\.atom\packages\build\node_modules\atom-package-deps\lib\index.js:55(anonymous function) @ C:\Users\phill\.atom\packages\build\node_modules\atom-package-deps\lib\index.js:55_tickCallback @ internal/process/next_tick.js:103
```

**Comment by noseglid** [comment]
Yea looks like you correctly got the new version, not change with the issue though.
I think the best course of action is to create a thread on the [Atom discuss board](https://discuss.atom.io/), as this is likely a problem with Atom or Oniguruma.

Oniguruma (and first-mate) is what is used for grammars (syntax highlighting, etc) in vanilla Atom so it "should" be possible.

**Comment by ThePhilderbeast** [comment]
I have started a thread, nothing insightful in there yet, but here is the link so you can follow along.

https://discuss.atom.io/t/errors-when-installing-a-plugin/32543/4

**Comment by ThePhilderbeast** [comment]
ok this just got weirder, I just downloaded the master branch, extracted and ran `apm install` and copied the resulting directory in, and it didn't throw any errors but I'm not getting any autocomplete prompts.

**Comment by noseglid** [comment]
Did you put it in your packages directory? Otherwise you must run `apm link` too to actually get it into Atom. It's good news that the installation went through though.

You must also have a `.classpath` file. It can be empty, in which case it will attempt to run java to see where the standard libraries are located and import autocompletion for those. You can also add additional classpaths (suchs as from maven or gradle) to that file.

**Comment by ThePhilderbeast** [comment]
its in the packages directory and atom is picking it up, I have tried with a .classpath file, and its still not working (I have tried both blank and pointing at the java lib dir, I am not getting an error on start up 

> Failed to collect java classes

**Comment by noseglid** [comment]
Please bear in mind that I have not tested this on Windows at all... it "should" work, but completely untested.

Where do you get `Failed to collect java classes` ? Is there anything in the console if you open devtools in Atom?

**Comment by ThePhilderbeast** [comment]
its coming up in one of those lovely red popup boxes, the console has nothing in it.

**Comment by noseglid** [comment]
I think there is something stopping it from working on windows. It's actually not `autocomplete-java-minus` which is collecting classes, but [java-classpath-registry](https://github.com/noseglid/java-classpath-registry)

There should be [more information](https://github.com/noseglid/java-classpath-registry/blob/master/lib/main.js#L27-L32) in that popup. What else is there?

**Comment by ThePhilderbeast** [comment]
So having a look at it, there is no other information in the error popup (seems strange looking at that code.)

all settings are default, the .classpath file is empty.

**Comment by noseglid** [comment]
Since you have the code, maybe you could add a `console.log` on `err` and see what it says?

**Comment by ThePhilderbeast** [comment]
I'm not conversant with node etc so my attempted at doing that was a total failure.

however it looks like loading the class path is broken in a whole bunch of ways so perhaps IO should make an issue on that package to look at them.

I did notice that if you don't have the project folder open before you open atom, it doesn't load at all.

**Comment by noseglid** [comment]
So, the [release notes for 1.10.0](https://github.com/atom/atom/releases/tag/v1.10.0) has this note:
- Package that depend on native modules now install more reliably

Does it work with `1.10.0` ?

**Comment by ThePhilderbeast** [comment]
still not working with 1.10.0, im getting the same errors

**Comment by Silvery-Corgan** [comment]
Hello. I am unable to install this package in Atom. Running Windows 10 x64. The error is:

`Failed to install java-plus dependencies`

No further info is specified

**Comment by Cuassar** [comment]
> oniguruma@6.1.1 install C:\Users\Catalin\AppData\Local\Temp\apm-install-dir-11729-5136-jhssa0\node_modules\autocomplete-java-minus\node_modules\oniguruma
> node-gyp rebuild


C:\Users\Catalin\AppData\Local\Temp\apm-install-dir-11729-5136-jhssa0\node_modules\autocomplete-java-minus\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\Catalin\AppData\Local\Temp\apm-install-dir-11729-5136-jhssa0
`-- (empty)


(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\Catalin\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Catalin\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\Catalin\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Catalin\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Catalin\AppData\Local\Temp\apm-install-dir-11729-5136-jhssa0\node_modules\autocomplete-java-minus\node_modules\oniguruma
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Catalin\AppData\Local\Temp\apm-install-dir-11729-5136-jhssa0\package.json'
npm WARN apm-install-dir-11729-5136-jhssa0 No description
npm WARN apm-install-dir-11729-5136-jhssa0 No repository field.
npm WARN apm-install-dir-11729-5136-jhssa0 No README data
npm WARN apm-install-dir-11729-5136-jhssa0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Catalin\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Catalin\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Catalin\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Catalin\\.atom\\.apmrc" "install" "C:\\Users\\Catalin\\AppData\\Local\\Temp\\d-11729-5136-1sdqkup\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Catalin\AppData\Local\Temp\apm-install-dir-11729-5136-jhssa0\npm-debug.log
npm ERR! code 1

Im running Windows 7 x64

**Comment by Kamik423** [comment]
just wanted to mention that this is still an issue. macOS 10.12.6 beta

```
> oniguruma@6.2.1 install /private/var/folders/7v/pfng2hz10rbfpbgb889l1g3w0000gn/T/apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or/node_modules/autocomplete-java-minus/node_modules/oniguruma
> node-gyp rebuild

/private/var/folders/7v/pfng2hz10rbfpbgb889l1g3w0000gn/T/apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or
└── (empty)


gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/7v/pfng2hz10rbfpbgb889l1g3w0000gn/T/apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or/node_modules/autocomplete-java-minus/node_modules/oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/7v/pfng2hz10rbfpbgb889l1g3w0000gn/T/apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or/package.json'
npm WARN apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or No description
npm WARN apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or No repository field.
npm WARN apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or No README data
npm WARN apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/hans/.atom/.apm/.apmrc" "--userconfig" "/Users/hans/.atom/.apmrc" "install" "/private/var/folders/7v/pfng2hz10rbfpbgb889l1g3w0000gn/T/d-117529-63413-1cx4wt2.ina3mobt9/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/7v/pfng2hz10rbfpbgb889l1g3w0000gn/T/apm-install-dir-117529-63413-1kbmp1j.5ss5ze61or/npm-debug.log
npm ERR! code 1
```

**Comment by noseglid** [comment]
I'm sorry. I haven't had time to look into this, and time looks scarce looking forward too.
I know they've made some changes to onigurama (to improve performance!) but I have no idea how it has impacted compatability. It could be that a simple bump of oniguramas version might resolve this.

I think this package has potiential to deliver a good Java development experience to Atom, but right now it looks like I won't be able to finish it.

If anyone is willing to take over, give me a shout!

**Comment by euisungkim** [comment]
I was having the same error and was able to fix by installing `libgcrypt`. Upon researching, I believe this problem is caused by node not installing a module. FYI, I installed node through `homebrew`. But I also updated/installed some things prior. I do not want to skip the steps so here is what I did:

1. Update homebrew: `brew upgrade`.
2. Change Python version to the latest python version 2 in PATH. Referring to this error: `gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.`
3. Installed `oniguruma`: `brew install oniguruma`
4. Updated `npm` to the latest version: `npm --version` -> `npm i -g npm`
5. Updated `node`: `brew upgrade node`
6. Installed `libgcrypt`: `brew install libgcrypt`

These allowed me to install this package in atom. Hope it helps.
